### ISSUE TITLE
Type 'JSONEncoder.OutputFormatting' has no member 'compact'

### ISSUE THREAD

**Issue by LucaFagan** [evermeer/Stuff#1]
Hello,
get the error Type 'JSONEncoder.OutputFormatting' has no member 'compact' in Codable.swift

I'm using xCode 9.1, swift_version is set to 4.0

Any Idea what's the problem ?

**Comment by evermeer** [comment]
I just pushed version 6.0 with the fix for this.

**Comment by LucaFagan** [comment]
I didn't expect an answer so fast. Thanks.

**Comment by eonist** [comment]
@evermeer there is a typo in the description of this repo. too small, not to small. Great work though ;)

**Comment by evermeer** [comment]
thanks @eonist, I changed it.
